wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.11.1
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691516543.791415
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 100
      3:
      - 23
      4: 3.11.1
      5: 0.15.8
      6: 4.31.0
      8:
      - 5
